src/richtext.js

This PR adds rel='noopener' to links that might contain target='_blank' attribute.
The rel='noopener' attribute prevents possible trivial phishing caused by exposed window.opener. For more information see https://mathiasbynens.github.io/rel-noopener/
Similar to https://github.com/prismicio/javascript-kit/pull/159
Signed-off-by: petetnt <pete.a.nykanen@gmail.com>

Add rel='noopener' to links with targets

---

package.json
src/richtext.js
src/uuid.js
test/richtext.js
yarn.lock

Fixes issue #6, and build's off of @elyobo's PR #7.
@elyobo's changes the kit to use the prismic-richtext indexes instead of the randomized uuid values. It also adds tests.
My addition fixes an issue in the original PR with br element indexing.

Stop using uuids as keys for elements.

---

package-lock.json
package.json

Since this package doesn't bundle React, that shouldn't be a dependency, but a peerDependency (and devDependency used for testing).
With the current setup (having React 15.6.1 as a dependency) you get two different React versions if the app you're using prismic-reactjs in is using React 16, which messes things up really bad.
This commit removes React as a dependency and adds it as a peerDependency and devDependency, thus solving this problem.

Change React to a dev and peer dependency

---

.babelrc
.travis.yml
package-lock.json
package.json
src/embeds.js
src/index.js
src/richtext.js
test/richtext.js
webpack.config.js

Previous serializer was embedding HTML without concern for existing script tags. I added a `createScript` method for FB, Insta and Twitter. In a next iteration, we could handle scripts like https://github.com/humanmade/react-oembed-container. In my opinion, creating a complete example on how to pass your own embed serializer should be enough - and really future proof as we would not handle anything on our side.
To test it, simply embed content from Twitter, Facebook and Instagram.
Will fix #17 too!

Better handling for oEmbeds

---

README.md
UPDATE-FROM-V0.md
src/Component.js

`renderAsText` property did not return a string. It was removed and replaced by `RichText.asText` as the standard method to return text strings. Docs were update in that direction

Removed `renderAsText` from component and documentation

---

package-lock.json
package.json
src/Component.js
src/richtext.js
test/richtext.js

Following #35, we needed a way to pass props (like `className`) to the wrapper element created by RichText.
Given this call to RichText:
```javascript
<RichText
render={myField}
Component="div"
className="my-class-name"
data-attribute="data"
/>
````
Your HTML markup should end up like this:
```html
<div class="my-class-name" data-attribute="data">
/* ... */
</div>
````
Note: users might forget that wrapper Component defaults to `React.Fragment` and therefore will not pass rest properly.

Richtext component `rest`property

---

package-lock.json
src/Component.js
src/richtext.js

In order to use custom React elements without heavily relying on `htmlSerializer`, a new `elements` prop has been created:
It takes an object of React components, accessible by "Elements" type (one of `heading1`, `em`, `strong`...)
Example use:
```javascript
<RichText elements={{ heading1: MyStyledComponent }} render={data.text} />
````

pass custom React elements via `elements` prop

---

.gitignore
package.json
typings/index.d.ts

In order to fix the following issue : #42 
Implementing a definition type for : RichText stateless component.
- Elements
- RichText
- Date
- Link
The _Date_ export might be called differently in the future, to avoid overwriting the default **Date** JS class.

Rich Text Typings

---

src/richtext.js

Returns correct type instead of wrong `undefined` type

Fix variable typo

---

package-lock.json
src/richtext.js

`serializeElement` now passes all its props to `React.createElement`. Because Prismic images format returns `src` instead of url, I added a special case for handling it.

Pass all props to `serializeElement`

---

typings/index.d.ts

Suggest updated typings for issue #42 
I am not completely familiar with the libraries and dependencies but these typings should be a bit clearer and usable.  
Currently the project does not build typings into its distribution, so I have copied these typings into my project as such:
```typescript
declare module 'prismic-reactjs' {
import React from 'react';
enum Elements {
heading1 = 'heading1',
heading2 = 'heading2',
heading3 = 'heading3',
heading4 = 'heading4',
heading5 = 'heading5',
heading6 = 'heading6',
paragraph = 'paragraph',
preformatted = 'preformatted',
strong = 'strong',
em = 'em',
listItem = 'list-item',
oListItem = 'o-list-item',
list = 'group-list-item',
oList = 'group-o-list-item',
image = 'image',
embed = 'embed',
hyperlink = 'hyperlink',
label = 'label',
span = 'span',
} …
```

Proposed TypeScript typings #42

---

index.d.ts

I ran into a few odd errors while trying to write an HTML serializer using these typings. Namely:
- `RichTextSpan`'s type property not accepting "em," which I think is valid
- The function passed to the `linkResolver` prop not expecting any arguments
- HTMLSerializer's `type` argument not corresponding with with RichTextBlock's `type`
I also made `text` and `spans` optional on `RichTextBlock`, because it can be an `Elements.image` type in some cases, and these have props like `url`, `dimensions`, `alt`, and `copyright`.
Let me know if I missed anything, I haven't tested every single rich text type yet.
Thanks for putting TypeScript typings in the repo. Much appreciated.

Update types for HTMLSerializer, RichTextBlock, and RichTextSpan

---

src/SliceZone.tsx
src/index.ts
test/SliceZone.test.tsx

This PR adds a `resolver` prop that matches that of `next-slicezone`. This change makes the migration path smoother for users upgrading existing projects.
It is marked as **deprecated** in favor of the `components` prop. `@prismicio/react`'s `<SliceZone>` will ultimately replace `next-slicezone`.
In a future major version, the `resolver` prop will be removed.
For reference, this is the type signature of the `resolver` function:
```typescript
/**
* Arguments for a `<SliceZone>` `resolver` function.
*/
type SliceZoneResolverArgs<TSlice extends SliceLike = SliceLike> = {
/**
* The Slice to resolve to a React component..
*/
slice: TSlice;
/**
* The name of the Slice.
*/
sliceName: TSlice["slice_type"];
/**
* The index of the Slice in the Slice Zone.
*/
i: number;
};
/**
* A function that …
```

feat: add `resolver` prop to SliceZone for backwards compatibility with `next-slicezone`

---

src/SliceZone.tsx

Related issue: #101
This PR fixes an issue where Slices could render in the wrong order in `<SliceZone>`.
The bug only occurs when the list of Slices changes after the first render. The bug occurs because the `key` prop is generated using the Slice's object. If multiple Slices contain the same payload (e.g. same Slice type, content, etc.), they would have duplicate keys.
To reduce the possibility of key collisions, this PR appends the Slice's index to the key.
🔑

fix: render Slices in the correct order in `<SliceZone>`

---

package-lock.json
package.json
src/SliceZone.tsx
src/lib/pascalCase.ts
test/SliceZone.test.tsx

`<SliceZone>`'s `resolve` prop is provided as a way to ease migration from `next-slicezone`. `next-slicezone`'s component uses a resolver function to convert a Slice's type to a React component. In this process, it converts the `slice_type` property into a pascalcased version.
This PR fixes a compatiblity issue by adding the pascalcase conversion.
*Note*: The `resolver` prop will be removed in a future version. When the prop is removed, the changes in this PR will also be removed.
🐫

fix: use pascalCase Slice type for `<SliceZone>` resolver

---

package.json

This PR updates the module exports to use `.mjs` rather than `.js`. This fixes an issue with Next.js 12 when deploying to Vercel (note that the problem only occurs in production).
`.mjs` originally was not used because it broken CRA 4. CRA 5 includes updates that resolves this issue (most likely the change to Webpack 5).
Related issues:
- https://github.com/prismicio/prismic-react/issues/108
- https://github.com/vercel/next.js/issues/30750

fix: use .mjs module exports

---

src/PrismicRichText.tsx
test/PrismicRichText.test.tsx

This PR automatically applies keys to custom components provided to `<PrismicRichText>`. Without the PR, React logs an error about missing keys if the a `key` prop is not explicitly given to each component.
More details: #114
🐺

fix: automatically assign keys to custom `<PrismicRichText>` components

---

package-lock.json
package.json
src/SliceZone.tsx
src/lib/pascalCase.ts

This PR moves the `PascalCase` type from [`type-fest`](https://github.com/sindresorhus/type-fest) into the project. This allows us to remove `type-fest` as a dependency.
Fixes #120
🐰

refactor: remove `type-fest` dependency

---

package.json

This PR removes the explicit ES Module declaration by removing `"type": "module"` from `package.json`.
Declaring the package as an ES Module has caused issues in the following circumstances:
- **Next.js on Vercel**: The entry file must use the `.mjs` extension to resolve correctly during server-rendered requests. This causes issues in build systems that do not recognize `.mjs` (e.g. Create React App). This only happens when deployed to Vercel in production. (See #108)
- **Create React App 4**: `.mjs` files are unsupported. It works with a `.js` file extension, which breaks Next.js support.
- **Create React App 5**: `.mjs` with `"type": "module"` is supported, but breaks backwards compatibility with CRA 4.
The most straightforward solution that ensures everything works out-of-the-box is to …

fix: remove ESM `package.json` declaration (fixes `'Element' is not exported from '@prismicio/richtext'`)

---

package-lock.json
package.json
src/PrismicRichText.tsx
src/PrismicText.tsx
test/PrismicRichText.test.tsx
test/PrismicText.test.tsx

This PR correctly handles all types of empty Rich Text fields when using `<PrismicRichText>` and `<PrismicText>`. It uses `@prismicio/helpers`'s `isFilled.richText()` helper internally.
This PR was done specifically to fix an unhandled case where a Rich Text field could contain a single empty `paragraph` block. This is treated as empty when using `isFilled.richText()`, but it was not handled properly in `@prismicio/react` before this PR.
🐕‍🦺

fix: detect empty Rich Text fields using `@prismicio/helpers`'s `isFilled.richText()`

---

src/PrismicLink.tsx
test/PrismicLink.test.tsx
test/__testutils__/renderJSON.ts

This PR adds support for forwarding refs to `<PrismicLink>` components. Before this PR, refs were ignored, meaning there was no way to target the rendered element.
In the following example, `ref` will contain a reference to the rendered `<a>` element.
```tsx
const Page = ({ document }) => {
const ref = useRef(null);
return (
<PrismicLink ref={ref} field={document.data.link}>
Click me!
</PrismicLink>
);
};
```
If a custom component is provided, the ref will be passed to the component. The custom component must handle the ref forwarding itself.
```tsx
const CustomComponent = React.forwardRef(({ href, children }, ref) => {
return <span ref={ref}>{children}</span>;
});
const Page = ({ document }) => {
const ref = useRef(null);
return (
<PrismicLink
ref={ref}
field={document.data.link} …
```

fix: forward refs to `<PrismicLink>` components

---

src/PrismicLink.tsx

This PR fixes a regression introduced by #131. Due to the way #131 implemented type-parameter-aware ref forwarding, projects using `@prismicio/react` could not manually declare a component's `displayName` property.
This PR also fixes a type bug related to the `ref` prop. It widens the ref element type to `Element` to support any valid HTML/SVG/etc. element. Note that an individual `<PrismicLink>` may not have enough information to determine which component is rendered since custom components can be provided to `<PrismicProvider>`. `Element` is the safest option.

fix: better support for custom `<PrismicLink>` components using `forwardRef()`

---

src/SliceZone.tsx
test/SliceZone.test.tsx

This PR adds support for Prismic's GraphQL API when using `<SliceZone>`.
The GraphQL API returns Slices with the following shape:
```json
{
"type": "foo",
"label": "bar",
"primary": {},
"items": []
}
```
The Rest API returns Slices with the following shape:
```json
{
"slice_type": "foo",
"slice_label": "bar",
"primary": {},
"items": []
}
```
To support the GraphQL API, `<SliceZone>` can now read a Slice's `slice_type` or `type` property to determine which component to render.
🐙

feat: support Prismic's GraphQL API in `<SliceZone>`

---

src/PrismicLink.tsx
src/PrismicProvider.tsx
src/PrismicRichText.tsx

This PR fixes a TypeScript type bug where provided Link Resolvers were not allowed to return anything except `string`.
The following components that accept a Link Resolver function have been fixed:
- `PrismicProvider`
- `PrismicRichText`
- `PrismicLink`
Fixes #137
🐟

fix: correct types for non-string Link Resolver functions

---

src/PrismicLink.tsx

This PR restores the default `React.AnchorHTMLAttributes` props on `<PrismicLink>`. This brings back support for common props like `className` and `onClick`.
See #145 for more details.
---
If you use `<PrismicLink>` with a component that does not behave like `<a>` (for example, it does not accept props for `className` or `onClick`), the following strategies can be used in your project.
In all three strategies, you would use a custom `<PrismicLink>` implementation built off `<PrismicLink>` provided by `@prismicio/react`.
(Note: This assumes PrismicLink is configured globally via `<PrismicProvider>` to render `<Link>` for internal links.)
You can take advantage of [TypeScript 4.7's Instantiation Expressions](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#instantiat …

fix: restore default `React.AnchorHTMLAttributes` props on `<PrismicLink>`

---

src/PrismicLink.tsx
test/PrismicLink.test.tsx
test/PrismicRichText.test.tsx

This PR adds functionality to automatic set `target="_blank" rel="noopener noreferrer"` when `href` is an external URL.
```tsx
<PrismicLink href="https://example.com">External</PrismicLink>
// <a href="https://example.com" target="_blank" rel="noopener noreferrer">External</a>
```
This behavior applies to both the `href` and `field` props. In the following example, assume `doc.data.linkField` resolves to an external URL.
```tsx
<PrismicLink field={doc.data.linkField}>External</PrismicLink>
// <a href="https://example.com" target="_blank" rel="noopener noreferrer">External</a>
```
`target` and `rel` can always be overriden by passing these props directly.
```tsx
<PrismicLink href="https://example.com" target={undefined}>
External
</PrismicLink>;
// <a …
```

feat(PrismicLink): automatically set `target="_blank" rel="noopener noreferrer"` when `href` is external

---

src/PrismicToolbar.tsx
test/PrismicToolbar.test.tsx

This PR patches `<PrismicToolbar>` to prevent the component's `<script>` element to execute in Happpy DOM environments. This is useful when using Happy DOM in tests, such as in Vitest.
The included patch will be pruned during code minification in non-test environments.
🐍

fix: do not execute `<PrismicToolbar>`'s script during Happy DOM tests

---

src/SliceZone.tsx
test/SliceZone.test.tsx

This PR changes `<SliceZone>` to accept untyped or partially typed Slices. The changes affect both the provided Slices (the `slices` prop) and components (the `components` prop).
It effectively removes any type checking between the `slices` and `components` props.
It also defaults Slice components' `slice` prop to `any` rather than `SliceLike`. This was done to support Prismic's Rest API and GraphQL API with the same set of types.
Developers can still provide types to their API responses via `@prismicio/client`'s type parameters and Slice components via `@prismicio/react`'s `SliceComponentProps`. This PR does not include breaking changes.
While these changes may seem like a step backwards, it broadens the library's support to include projects with insufficient type data. Today, projects …

fix: support untyped or partially typed Slices in `<SliceZone>`

---

package-lock.json
package.json
src/PrismicLink.tsx
test/PrismicLink.test.tsx

This PR changes `<PrismicLink>`'s development-only behavior to warn rather than throw when given an invalid Link field or Prismic document (in most cases; see the note below).
In addition to reducing the severity of an invalid field or document, this PR also fixes a bug where a valid unfilled Link field (i.e. a field that a content writer did not fill in) was treated as invalid. Unfilled Link fields are now treated as valid.
**Note**: `<PrismicLink>` will still throw if a `link_type` property is missing from the provided `field` prop value. `link_type` is required to detect the type of link and is populated even for unfilled Link fields.
(Thanks to @kb1995 for [discovering this bug](https://github.com/prismicio/prismic-react/issues/150#issuecomment-1147327993)!)
🐱

fix: prefer warning over throwing when `<PrismicLink>` is given an invalid prop in development

---

src/PrismicLink.tsx
test/PrismicLink.test.tsx

This PR fixes a bug in `<PrismicLink>` where it logged a console warning about missing Link field properties when given an empty Link field value. Empty link values are valid and should not trigger the warning.
The issue was unknown because the test to check this exact case was written incorrectly ([see the fix](https://github.com/prismicio/prismic-react/pull/163/files#diff-fdb4f3665170c51342618d4178b9cfba515f44fb94272c3df92a9221cd174360L483-R483)).
Fixes #161
Thanks to @ReeceM for uncovering the issue!
🐈

fix(PrismicLink): do not warn about missing field properties if the Link field is empty

---

src/PrismicLink.tsx
test/PrismicLink.test.tsx

This PR changes `<PrismicLink>` such that `target="_blank"` is only automatically set when a Link field's "Open in new tab" checkbox is checked.
Before this PR, `<PrismicLink>` would set `target="_blank"` when "Open in new tab" was checked **or** when the URL was external (i.e. started with `https://`).
Automatically opening external URLs in new windows was originally introduced as a convenience. However, this meant the "Open in new tab" checkbox was ignored in some cases; if the checkbox was purposely unchecked, the link would still open in a new window. This is considered a bug.
`rel="noopener noreferrer"` will continue to be set automatically if `target="_blank"` is set.
Fixes #171
🐛

fix(PrismicLink): only set `target="_blank"` when "Open in new tab" is checked

---

messages/classname-is-not-a-valid-prop.md
src/PrismicText.tsx
src/react-server/PrismicRichText.tsx
test/PrismicText.test.tsx
test/react-server/PrismicRichText.test.tsx

This PR adds a development-only warning when a `className` prop is passed to the following components:
- `<PrismicRichText>`
- `<PrismicText>`
These components do not support a `className` prop, but their purpose suggests they do.
See the `classname-is-not-a-valid-prop.md` message for more details.
🐝

fix: warn when passing `className` to `<PrismicRichText>` or `<PrismicText>`

---

src/SliceZone.tsx
src/index.ts
test/SliceZone.test.tsx

This PR restores the `resolver` prop in `<SliceZone>`.
This prop is deprecated and should not be used. It will be removed in the next major version. It was mistakenly removed in a minor release (v2.6.0).

fix(SliceZone): restore `resolver` prop

---

src/PrismicImage.tsx
test/PrismicImage.test.tsx
test/__testutils__/renderJSON.ts

This PR fixes a case where `<PrismicImage>` would not remove Imgix parameters when used in React Server Components (RSC).
RSCs serialize prop values before sending to Client Compomnents like `<PrismicImage>`. During this serialization, `undefined` values are removed from objects, which `<PrismicImage>`'s underlying Imgix param library, `imgix-url-builder`, relies on to remove parameters.
To fix this, `imgixParams` now accepts `null` in place of `undefined`.
**`null` should be used to remove parameters when `<PrismicImage>` is used in Server Components.**
```tsx
// In a Server Component
<PrismicImage
field={myImageField}
imgixParams={{
auto: null, // undefined will not work
}}
/>
```
```tsx
// In a Client Component
<PrismicImage
field={myImageField}
imgixParams={{
auto: undefined, // null …
```

fix(PrismicImage): allow removing Imgix params in React Server Components using `null`

---

src/PrismicLink.tsx
src/PrismicRichText.tsx

Fixing issue when using Next.JS  with Typescript with the mandatory `--isolatedModule` set to `true`. This requires having all type exports as `export type`. The change also keeps the type export consistent with the `index.ts` type exports.
Fixes: `Type error: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.`
🚘

fix: resolve TypeScript build error in projects using `--isolatedModules`

---

src/SliceZone.tsx
test/SliceZone.test.tsx

Mapped slices would cause the `<TODOSliceComponent />` component to throw because of a different interface used by mapped slices (slice type being top level instead of nested under the `slice` property).
This standardizes the props given to `<TODOSliceComponent />` so everything keeps working smoothly based on our Svelte implementation: https://github.com/prismicio/prismic-svelte/blob/master/src/SliceZone/SliceZone.svelte#L118-L128
I first explored adapting the `<TODOSliceComponent />` to support different interfaces instead, but it resulted in messier code in my opinion: https://github.com/prismicio/prismic-vue/blob/95d5771b51dc45df5bd6663178afceae8942dc4c/src/components/SliceZone.ts#L263-L280 (hence the sister PR for Vue: https://github.com/prismicio/prismic-vue/pull/70)

fix: `<TodoSliceComponent />` compat with Slice Mapper

---

package-lock.json
package.json

- Add support for React 19 in the library's peer dependencies
Resolves [DT-2165](https://linear.app/prismic/issue/DT-2165/aauser-i-can-use-prismicioreact-with-react-19)

Support React 19

---

.github/workflows/ci.yml
CHANGELOG.md
examples/with-typescript/index.tsx
examples/with-typescript/package.json
package-lock.json
package.json
src/react-server/PrismicLink.tsx
src/useStatefulPrismicClientMethod.ts
test/PrismicLink.test.tsx
test/react-server/PrismicRichText.test.tsx

Resolves: [DT-2272](https://linear.app/prismic/issue/DT-2272/aadev-i-can-use-prismic-sdks-with-support-link-text)
- Support link text 
- Update example with new usage

feat: support link text

---

package-lock.json
src/react-server/PrismicRichText.tsx
test/react-server/PrismicRichText.test.tsx

**Resolves**: https://prismic-team.slack.com/archives/C014VAACCQL/p1729780207755199
This PR updates the default richtext serializer to honor the `direction` property of rich text nodes and adds the appropriate `dir` attribute on right-to-left text nodes. `undefined` should serialize to "no attribute" in React according to the types.
P.S. Are we considering releasing a major of this kit to eliminate the dependency on `@prismicio/types`/`@prismicio/richtext`? It's not that much of a big deal for now but might cause more issues later on.
Related:
- `@prismicio/client` PR: https://github.com/prismicio/prismic-client/pull/357
- `@prismicio/svelte` PR: https://github.com/prismicio/prismic-svelte/pull/24
[^1]:
Please use these labels when submitting a review:
:question: #ask:&ensp;Ask a …

fix(helpers): add missing `dir` attribute for right-to-left languages

---

examples/custom-slicezone-props/index.tsx
examples/router-link/index.tsx
examples/with-global-configuration/index.tsx
examples/with-typescript/index.tsx
src/PrismicImage.tsx
src/PrismicLink.tsx
src/PrismicProvider.tsx
src/PrismicText.tsx
src/SliceZone.tsx
src/react-server/PrismicLink.tsx
src/react-server/PrismicRichText.tsx
src/react-server/unsupported.ts
src/types.ts
test/SliceZone.test.tsx

This PR updates `@prismicio/react` to be compatible with React 18 and 19 TypeScript types.
React 19 requires changing `JSX.Element` to `React.JSX.Element` ([see the React 19 release notes](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#the-jsx-namespace-in-typescript)). The change is compatible with React 18's TypeScript types.

fix: use React 18 and 19 compatible types

---

e2e-projects/nextjs/app/PrismicTable/page.tsx
package-lock.json
package.json
src/PrismicTable.tsx

**Resolves**: N/A
This PR edits #219 with the following changes:
- Uses newly exported table field types from `@prismicio/client`. See https://github.com/prismicio/prismic-client/pull/377.
- Removes the `tableComponents` prop. It was used in the example but not intended for the final API.
- Makes the assumption that function-based rich text serializers are not supported.
> [!IMPORTANT]
> The new `@prismicio/client` table types are not published yet, causing tests to fail. `@prismicio/client` should be updated once https://github.com/prismicio/prismic-client/pull/377 is merged and published.
[^1]:
Please use these labels when submitting a review:
:question: #ask:&ensp;Ask a question.
:bulb: #idea:&ensp;Suggest an idea.
:warning: #issue:&ensp;Strongly suggest a change.
:tada: …

feat: remove `tableComponents` prop

---

e2e-projects/nextjs/app/PrismicTable/page.tsx
e2e-projects/nextjs/package.json
e2e-projects/nextjs/prismic-types.d.ts
package-lock.json
package.json
src/PrismicTable.tsx
src/index.ts
tests/PrismicTable.spec.ts
tests/infra/content/index.ts
tests/infra/content/table.ts
tests/infra/setup.ts

**Resolves**: [DT-2553](https://linear.app/prismic/issue/DT-2553/%5Bm%5D-aadev-i-can-use-prismictable-in-next)
This PR adds a PrismicTable component and tests.
- [Table Field PRD](https://www.notion.so/prismic/PRD-Table-Fields-4c56193e5fbd40dcbeaef7ce5531d03c#17d3bee08669806a855df83b2b0d6b8b)
N/A
[^1]:
Please use these labels when submitting a review:
:question: #ask:&ensp;Ask a question.
:bulb: #idea:&ensp;Suggest an idea.
:warning: #issue:&ensp;Strongly suggest a change.
:tada: #nice:&ensp;Share a compliment.

feat: add PrismicTable component
